### ISSUE TITLE
issue from newbie

### ISSUE THREAD

**Issue by kjhoot** [linuxmint/mintreport#69] opened 2021-03-26 22:05 UTC
I may not be able to help with this as I'm a newbie with little technical skills, but my new installation of linux mint keeps freezing (mouse, or if it moves, doesn't work, and screen) when I'm using the net. Some of these problems seemed to start after I set up a few web apps - I removed them now but the problem remains. Also, I noticed either the swap was high when the last freeze occurred.

I will just share my recent logs and system description, if that is useful: 

LOGS

17:14:20 sudo:      ? : a password is required ; TTY=unknown ; PWD=/home/? ; USER=root ; COMMAND=/sbin/hddtemp -nq -u C /dev/sda
17:10:58 pulseaudio: GetManagedObjects() failed: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
17:10:58 pulseaudio: GetManagedObjects() failed: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
17:10:31 pulseaudio: Error opening PCM device front:0: No such file or directory
17:10:31 pulseaudio: Error opening PCM device front:0: No such file or directory
17:10:31 lightdm: gkr-pam: unable to locate daemon control file
17:10:31 lightdm: gkr-pam: unable to locate daemon control file
17:10:15 lightdm: PAM adding faulty module: pam_kwallet5.so
17:10:15 lightdm: PAM unable to dlopen(pam_kwallet5.so): /lib/security/pam_kwallet5.so: cannot open shared object file: No such file or directory
17:10:15 lightdm: PAM adding faulty module: pam_kwallet.so
17:10:15 lightdm: PAM unable to dlopen(pam_kwallet.so): /lib/security/pam_kwallet.so: cannot open shared object file: No such file or directory
13:18:15 pulseaudio: GetManagedObjects() failed: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
13:17:50 lightdm: PAM adding faulty module: pam_kwallet5.so
12:48:53 hp-makeuri: hp-makeuri[3031]: error: Device not found
12:46:35 hpfax: [2874]: error: Failed to create /var/spool/cups/tmp/.hplip
12:36:39 kernel: Out of memory: Killed process 1002 (pdftoraster) total-vm:5452200kB, anon-rss:3516140kB, file-rss:0kB, shmem-rss:0kB, UID:0 pgtables:10428kB oom_score_adj:0
12:28:50 pulseaudio: GetManagedObjects() failed: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
12:28:23 lightdm: gkr-pam: unable to locate daemon control file
12:28:07 pulseaudio: GetManagedObjects() failed: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
12:27:46 lightdm: PAM adding faulty module: pam_kwallet5.so
12:27:22 ntpd: error resolving pool 2.ubuntu.pool.ntp.org: Name or service not known (-2)
12:27:14 avahi-daemon: chroot.c: open() failed: No such file or directory
12:27:06 kernel: b43-phy0 ERROR: You must go to http://wireless.kernel.org/en/users/Drivers/b43#devicefirmware and download the correct firmware for this driver version. Please carefully read all instructions on this website.
12:27:00 kernel: ACPI Error: Aborting method \_SB.PCI0.OVGA.DD03._BQC due to previous error (AE_ALREADY_EXISTS) (20190816/psparse-529)
12:27:00 kernel: ACPI Error: Aborting method \_SB.PCI0.OVGA.DD03._BQC due to previous error (AE_ALREADY_EXISTS) (20190816/psparse-529)
12:27:00 kernel: ACPI Error: Aborting method \_SB.PCI0.OVGA.DD03.GBQC due to previous error (AE_ALREADY_EXISTS) (20190816/psparse-529)
12:27:00 kernel: ACPI Error: AE_ALREADY_EXISTS, During name lookup/catalog (20190816/psobject-220)
12:27:00 kernel: ACPI BIOS Error (bug): Failure creating named object [\_SB.PCI0.OVGA.DD03.GBQC._T1], AE_ALREADY_EXISTS (20190816/dswload2-326)

SYSTEM:

System:    Kernel: 5.4.0-70-generic x86_64 bits: 64 compiler: gcc v: 9.3.0 Desktop: Xfce 4.14.2 
           tk: Gtk 3.24.13 wm: xfwm4 dm: LightDM Distro: Linux Mint 20.1 Ulyssa 
           base: Ubuntu 20.04 focal 
Machine:   Type: Laptop System: Hewlett-Packard product: HP Pavilion dv6 Notebook PC v: Rev 1 
           serial: <filter> Chassis: Quanta type: 10 serial: <filter> 
           Mobo: Quanta model: 3627 v: 18.42 serial: <filter> BIOS: Hewlett-Packard v: F.33 
           date: 08/31/2009 
Battery:   ID-1: BAT0 charge: 38.4 Wh condition: 40.1/47.5 Wh (84%) volts: 12.1/10.8 
           model: Hewlett-Packard Primary serial: <filter> status: Unknown 
CPU:       Topology: Dual Core model: Intel Core2 Duo T6500 bits: 64 type: MCP arch: Penryn rev: A 
           L2 cache: 2048 KiB 
           flags: lm nx pae sse sse2 sse3 sse4_1 ssse3 bogomips: 8380 
           Speed: 2095 MHz min/max: 1200/2100 MHz Core speeds (MHz): 1: 2095 2: 2095 
Graphics:  Device-1: Intel Mobile 4 Series Integrated Graphics vendor: Hewlett-Packard 
           driver: i915 v: kernel bus ID: 00:02.0 chip ID: 8086:2a42 
           Display: x11 server: X.Org 1.20.9 driver: modesetting unloaded: fbdev,vesa 
           compositor: compton resolution: 1366x768~60Hz 
           OpenGL: renderer: Mesa DRI Mobile Intel GM45 Express (CTG) v: 2.1 Mesa 20.2.6 
           direct render: Yes 
Audio:     Device-1: Intel 82801I HD Audio vendor: Hewlett-Packard driver: snd_hda_intel v: kernel 
           bus ID: 00:1b.0 chip ID: 8086:293e 
           Sound Server: ALSA v: k5.4.0-70-generic 
Network:   Device-1: Broadcom and subsidiaries BCM4312 802.11b/g LP-PHY 
           vendor: Hewlett-Packard U98Z049.00 Wireless Mini PCIe Card driver: b43-pci-bridge 
           v: N/A port: 7000 bus ID: 02:00.0 chip ID: 14e4:4315 
           Device-2: Realtek RTL810xE PCI Express Fast Ethernet vendor: Hewlett-Packard 
           driver: r8169 v: kernel port: 5000 bus ID: 03:00.0 chip ID: 10ec:8136 
           IF: enp3s0 state: up speed: 100 Mbps duplex: full mac: <filter> 
Drives:    Local Storage: total: 298.09 GiB used: 24.72 GiB (8.3%) 
           ID-1: /dev/sda vendor: Seagate model: ST9320325AS size: 298.09 GiB speed: 3.0 Gb/s 
           serial: <filter> 
Partition: ID-1: / size: 291.92 GiB used: 24.72 GiB (8.5%) fs: ext4 dev: /dev/sda5 
USB:       Hub: 1-0:1 info: Full speed (or root) Hub ports: 4 rev: 2.0 chip ID: 1d6b:0002 
           Device-1: 1-1:2 info: Realtek USB 2.0 multicard reader type: Mass Storage 
           driver: ums-realtek rev: 2.0 chip ID: 0bda:0158 
           Hub: 2-0:1 info: Full speed (or root) Hub ports: 8 rev: 2.0 chip ID: 1d6b:0002 
           Device-2: 2-4:2 info: Quanta HP Webcam type: Video driver: uvcvideo rev: 2.0 
           chip ID: 0408:03f1 
           Hub: 3-0:1 info: Full speed (or root) Hub ports: 2 rev: 1.1 chip ID: 1d6b:0001 
           Hub: 4-0:1 info: Full speed (or root) Hub ports: 2 rev: 1.1 chip ID: 1d6b:0001 
           Hub: 5-0:1 info: Full speed (or root) Hub ports: 2 rev: 1.1 chip ID: 1d6b:0001 
           Hub: 6-0:1 info: Full speed (or root) Hub ports: 2 rev: 1.1 chip ID: 1d6b:0001 
           Hub: 7-0:1 info: Full speed (or root) Hub ports: 2 rev: 1.1 chip ID: 1d6b:0001 
           Hub: 8-0:1 info: Full speed (or root) Hub ports: 2 rev: 1.1 chip ID: 1d6b:0001 
Sensors:   System Temperatures: cpu: 66.0 C mobo: N/A 
           Fan Speeds (RPM): N/A 
Repos:     No active apt repos in: /etc/apt/sources.list 
           Active apt repos in: /etc/apt/sources.list.d/nordvpn.list 
           1: deb https: //repo.nordvpn.com//deb/nordvpn/debian stable main
           Active apt repos in: /etc/apt/sources.list.d/official-package-repositories.list 
           1: deb http: //mirror.clarkson.edu/linuxmint/packages ulyssa main upstream import backport
           2: deb http: //archive.ubuntu.com/ubuntu focal main restricted universe multiverse
           3: deb http: //archive.ubuntu.com/ubuntu focal-updates main restricted universe multiverse
           4: deb http: //archive.ubuntu.com/ubuntu focal-backports main restricted universe multiverse
           5: deb http: //security.ubuntu.com/ubuntu/ focal-security main restricted universe multiverse
           6: deb http: //archive.canonical.com/ubuntu/ focal partner
Info:      Processes: 254 Uptime: 5h 21m Memory: 3.75 GiB used: 1.22 GiB (32.5%) Init: systemd 
           v: 245 runlevel: 5 Compilers: gcc: 9.3.0 alt: 9 Client: Unknown python3.8 client 
           inxi: 3.0.38

**Comment by xenopeek** [comment] 2021-03-27 16:00
This looks unrelated to the System Reports tool (mintreport) so closing it here. For help with troubleshooting your issue instead suggest you make a new topic on the support forums: https://forums.linuxmint.com/. If during troubleshooting it's determined the cause is a bug in a component developed or maintained by Linux Mint you can open an issue on that component.

**Closed by xenopeek** 2021-03-27 16:00 UTC
